config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

   root 'tracked_urls#index'

    resources :tracked_urls, only: [:index] do
      member do
        get 'visit'
      end
    end

    mount API => '/'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/destination_url.rb
class DestinationUrl < ActiveRecord::Base
  has_many :tracked_urls
  validates_presence_of :name

  accepts_nested_attributes_for :tracked_urls
end

app/models/tracked_url.rb
class TrackedUrl < ActiveRecord::Base
  belongs_to :destination_url
  has_many :visitors

  validates_presence_of :destination_url, if: :create_via_admin
  validates_presence_of :name

  attr_accessor :create_via_admin
end

app/models/visitor.rb
class Visitor < ActiveRecord::Base
  belongs_to :tracked_url, counter_cache: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tracked_urls_controller.rb
class TrackedUrlsController < ApplicationController
  def index
    @tracked_urls = TrackedUrl.where(status: true).order(:name).page(params[:page]).per(2)
  end

  def visit
    @tracked_url = TrackedUrl.find(params[:id])
    visitor = Visitor.new(tracked_url_id: @tracked_url.id, ip_add: request.ip)
    if visitor.save
      flash[:info] = 'You visit got recorded successfully.'
    else
      flash[:error] = 'You visit could not be recorded.'
    end
    record_extra_info_from_ip(visitor)
    redirect_to root_url
  end


  def record_extra_info_from_ip(visitor)
    #For a bigger app this should be in a separate file but its ok for this scale.
    #TODO cater timeout here but i think this is out of scope for the demo project. Will cater it later.
    response = HTTParty.get("http://ip-api.com/json/#{request.ip}")
    if response && response.parsed_response
      visitor.country = response.parsed_response['country']
      visitor.city = response.parsed_response['city']
      visitor.timezone = response.parsed_response['timezone']
      visitor.zipcode = response.parsed_response['zipcode']
      visitor.save
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/destination_urls_helper.rb
module DestinationUrlsHelper
end

app/helpers/tracked_urls_helper.rb
module TrackedUrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SUG</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <%= csrf_meta_tags %>
</head>


<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Generator</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">Home</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>
<br>
<br>
<div class="container theme-showcase">

  <%= yield %>

</div> <!-- /container -->


</body>
</html>


</html>

app/views/shared/_flash.html.erb
<% if (flash[:notice]) %>
    <div class="alert alert-info">
      <strong>Info!</strong> <%= flash[:notice] %>
    </div>
<% elsif (flash[:error]) %>
    <div class="alert alert-danger">
      <strong>Info!</strong> <%= flash[:error] %>
    </div>
<% end %>

app/views/tracked_urls/index.html.erb
<br>
<h3><b>Tracked Urls<b/></h3>
<p>Click on the links to visit them.</p>

<%= render partial: '/shared/flash.html.erb' %>

<% classes = ['active', 'success', 'info', 'warning', 'danger'] %>
<table class="table">
  <thead>
      <tr>
          <th>Link</th>
          <th>Visit Button</th>
      </tr>
  </thead>
    <% @tracked_urls.each_with_index do |tracked_url, i| %>
      <tbody>
          <tr class="<%= classes[i] %>">
              <td><%= tracked_url.name %></td>
              <td><%= link_to('Visit Me', visit_tracked_url_path(tracked_url), class: 'btn btn-sm btn-visit', data: {destination: tracked_url.destination_url.name} ) %></td>
          </tr>
      </tbody>
    <% end %>
</table>
<%= paginate @tracked_urls %>

app/views/tracked_urls/visit.html.erb
<h1>TrackedUrls#visit</h1>
<p>Find me in app/views/tracked_urls/visit.html.erb</p>